<a href="https://colab.research.google.com/github/nishita-ds/pyTorch-learning/blob/main/03-nn-module/nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [2]:
# create dataset
features=torch.rand(10,5)

# create model
model= Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.6570],
        [0.6465],
        [0.6589],
        [0.6573],
        [0.6508],
        [0.6648],
        [0.6613],
        [0.6637],
        [0.6470],
        [0.6600]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
model.linear2.weight

Parameter containing:
tensor([[ 0.1690, -0.2208,  0.2807]], requires_grad=True)

In [4]:
!pip install torchinfo

In [5]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [6]:
# create sequential container
class Model1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out


In [7]:
# create dataset
features=torch.rand(10,5)

# create model
model1= Model1(features.shape[1])

# call model for forward pass
model1(features)

tensor([[0.3913],
        [0.4010],
        [0.3834],
        [0.4102],
        [0.3809],
        [0.3849],
        [0.3794],
        [0.4318],
        [0.4121],
        [0.4237]], grad_fn=<SigmoidBackward0>)

In [8]:
from torchinfo import summary
summary(model1,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00