<a href="https://colab.research.google.com/github/nishita-ds/pyTorch-learning/blob/main/01-tensors/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available!
Using GPU: Tesla T4


# Creating a Tensor

In [ ]:
# using empty
a=torch.empty(2,3)
a

tensor([[1.4125e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8217e-44, 0.0000e+00]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
b=torch.rand(2,3)
b

tensor([[0.5401, 0.5395, 0.5834],
        [0.3316, 0.7847, 0.7288]])

In [ ]:
# using of seed----give same random values everytime
# set the seed for generating random numbers
torch.manual_seed(100)
a=torch.rand(2,3)
a

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(0,10,4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [ ]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[132756775685520,       437289424,       437402912],
        [      437397424,               0,       437302016]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Type

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([2.0,1.0],dtype=torch.int32)

tensor([2, 1], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations



> 1.Scalar Operation



In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
# substraction
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
# multiplication
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [ ]:
# division
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [ ]:
# int division
(x*100)//3
# mod
((x*100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
# add
a +b
# sub
a-b
# multiply
a*b
# division
a/b
# power
a**b
# mod
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [ ]:
# abs absolute value
torch.abs(x)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative value
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**3.Reduction operation**

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10)
e

tensor([[8, 0, 7],
        [0, 0, 9]])

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

print(e)
print(f)

tensor([[5., 7., 3.],
        [9., 4., 0.]])
tensor([[5., 7., 5.],
        [9., 9., 7.]])


In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e,dim=0)
# sum along rows
torch.sum(e,dim=1)

tensor([15., 13.])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e,dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max and min
torch.min(e)
torch.max(e)

tensor(9.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [ ]:
# variance
torch.var(e)

tensor(9.8667)

In [ ]:
# argmax
torch.argmax(e)

tensor(3)

In [ ]:
# argmin
torch.argmin(e)

tensor(5)

***4.Matrix operations***

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [ ]:
# matrix multiplication
torch.matmul(f,g)

tensor([[137, 117],
        [139, 130]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[6., 1., 5.],
        [5., 0., 4.],
        [3., 8., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(-20.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 1.6000, -1.6000, -0.2000],
        [ 1.4000, -1.6500, -0.0500],
        [-2.0000,  2.2500,  0.2500]])

**5.Comparison operations**

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[3, 3, 5],
        [0, 6, 4]])
tensor([[0, 8, 4],
        [7, 2, 3]])


In [ ]:
# greater than
i>j

# less than
i<j

# equal to
i==j

# not equal to
i!=j

# greater than equal to
i>=j

# less than equal to
i<=j


tensor([[False,  True, False],
        [ True, False, False]])

**6.Special functions**

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [ ]:
# log
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [ ]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [ ]:
# sqrt
torch.sqrt(k)
# sigmoid
torch.sigmoid(k)
# softmax
torch.softmax(k,dim=0)
# relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

### Inplace Operation

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [ ]:
m+n
# result stored in new tensor


tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [ ]:
m.add_(n)
# add underscore function

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [ ]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [ ]:
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [ ]:
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

#### Copying a Tensor

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
# To copy the values of a ,we can use assignment operator a=b but when updating a also update b
b=a.clone()
b


tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
a[0][0]=10
a

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [ ]:
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
print(id(a))
print(id(b))

132756619630528
132751270706016


# Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)


tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
b = a.to(device)

In [ ]:
b+5

tensor([[5.4175, 5.0340, 5.9157],
        [5.3079, 5.6269, 5.8277]], device='cuda:0')

In [ ]:
import time

# Define the size of the matrices
size=1000 #large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2=torch.randn(size,size)

# Measure time on CPU
start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time() - start_time

print(f'Time on CPU: {cpu_time:.4f} seconds')


# Move matrices to GPU
matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')

# Measure time on GPU
start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()  #Ensure all GPU operations are complete
gpu_time=time.time() - start_time

print(f'Time on GPU: {gpu_time:.4f} seconds')

# compare results
print("\nSpeedup (CPU time/ GPU time):",cpu_time/gpu_time)

Time on CPU: 0.0398 seconds
Time on GPU: 0.1184 seconds

Speedup (CPU time/ GPU time): 0.3363900576232475


# Reshaping Tensors

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.8485, 0.4441, 0.5472, 0.0124],
         [0.0467, 0.2321, 0.9232, 0.6272],
         [0.9363, 0.7697, 0.9526, 0.6208]],

        [[0.0330, 0.6702, 0.2086, 0.7164],
         [0.1627, 0.5908, 0.2001, 0.7692],
         [0.3234, 0.5739, 0.9485, 0.2220]]])

In [ ]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
torch.from_numpy(c)

tensor([1, 2, 3])